version: '3.9'

services:
  db:
    image: postgres:15
    container_name: wolf_game_db
    restart: always
    environment:
      POSTGRES_DB: wolf_game
      POSTGRES_USER: wolf_admin
      POSTGRES_PASSWORD: motdepasse_secure
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  pgdata:
    driver: local