services:
  db:
    image: postgres:15
    container_name: wolf_game_db
    restart: always
    environment:
      POSTGRES_DB: wolf_game
      POSTGRES_USER: wolf_admin
      POSTGRES_PASSWORD: motdepasse_secure
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wolf_admin -d wolf_game"]
      interval: 5s
      timeout: 5s
      retries: 5

  admin:
    build: ./wolf-admin-engine
    container_name: wolf_admin
    restart: unless-stopped
    environment:
      FLASK_ENV: development
      DATABASE_URL: "postgresql://wolf_admin:motdepasse_secure@db/wolf_game"
      HTTP_SERVER_HOST: "http_server"
      HTTP_SERVER_PORT: "9000"
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
      http_server:
        condition: service_started
    volumes:
      - ./wolf-admin-engine:/app

  http_server:
    build: ./wolf-http-server
    container_name: wolf_http_server
    ports:
      - "8080:8080"  # Port HTTP
      - "9000:9000"  # Port TCP pour les notifications
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://wolf_admin:motdepasse_secure@db/wolf_game"
      HTTP_SERVER_PORT: "9000"

volumes:
  pgdata:
    driver: local