#  docker-compose.yml
services:
  db:
    image: postgres:15
    container_name: wolf_game_db
    restart: always
    environment:
      POSTGRES_DB: wolf_game
      POSTGRES_USER: wolf_admin
      POSTGRES_PASSWORD: motdepasse_secure
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:  # <-- Déplacé au niveau des autres propriétés du service db
      test: ["CMD-SHELL", "pg_isready -U wolf_admin -d wolf_game"]
      interval: 5s
      timeout: 5s
      retries: 5

  admin:
    build: ./wolf-admin-engine
    container_name: wolf_admin
    restart: unless-stopped
    environment:
      FLASK_ENV: development
      DATABASE_URL: "postgresql://wolf_admin:motdepasse_secure@db/wolf_game"
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./wolf-admin-engine:/app

  http_server:
    build: ./wolf-http-server
    container_name: wolf_http_server
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://wolf_admin:motdepasse_secure@db/wolf_game"

  tcp_server:
    build: ./wolf-tcp-server
    container_name: wolf_tcp_server
    restart: unless-stopped
    ports:
      - "8888:8888"
    depends_on:
      db:
        condition: service_healthy  # Corrigé "ahealthy" à "healthy"
    environment:
      DATABASE_URL: "postgresql://wolf_admin:motdepasse_secure@db/wolf_game"

volumes:
  pgdata:
    driver: local